In [1]:
import numpy as np

In [12]:
A=np.array([[3,0],[1,2]])

In [3]:
P=np.array([[1,0],[1,1]])

In [4]:
P

array([[1, 0],
       [1, 1]])

In [6]:
P_1=np.linalg.inv(P)

In [9]:
D=np.array([[3,0],[0,2]])

In [13]:
A2=P@D@P_1

In [14]:
A-A2

array([[0., 0.],
       [0., 0.]])

In [15]:
P_1@A@P

array([[3., 0.],
       [0., 2.]])

In [16]:
A=np.array([[1,0,0],[3,-2,0],[2,3,4]])

In [17]:
P=np.array([[1,0,0],[1,-2,0],[-5/3,1,1]])

In [18]:
P_1=np.linalg.inv(P)

In [19]:
P_1@A@P

array([[ 1.00000000e+00,  2.66453526e-16,  0.00000000e+00],
       [ 1.11022302e-16, -2.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  4.44089210e-16,  4.00000000e+00]])